
id: proteingym-dms/OXDA_RHOTO_Vanella_2023_activity
name: OXDA_RHOTO_Vanella_2023_activity
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/OXDA_RHOTO_Vanella_2023_activity/description.md
preparer: biomlbench.tasks.proteingym-dms.OXDA_RHOTO_Vanella_2023_activity.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: OXDA_RHOTO_Vanella_2023_activity

dataset:
  answers: proteingym-dms/OXDA_RHOTO_Vanella_2023_activity/prepared/private/answers.csv
  sample_submission: proteingym-dms/OXDA_RHOTO_Vanella_2023_activity/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.OXDA_RHOTO_Vanella_2023_activity.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
