
id: proteingym-dms/P84126_THETH_Chan_2017
name: P84126_THETH_Chan_2017
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/P84126_THETH_Chan_2017/description.md
preparer: biomlbench.tasks.proteingym-dms.P84126_THETH_Chan_2017.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: P84126_THETH_Chan_2017

dataset:
  answers: proteingym-dms/P84126_THETH_Chan_2017/prepared/private/answers.csv
  sample_submission: proteingym-dms/P84126_THETH_Chan_2017/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.P84126_THETH_Chan_2017.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
