
id: proteingym-dms/SBI_STAAM_Tsuboyama_2023_2JVG
name: SBI_STAAM_Tsuboyama_2023_2JVG
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/SBI_STAAM_Tsuboyama_2023_2JVG/description.md
preparer: biomlbench.tasks.proteingym-dms.SBI_STAAM_Tsuboyama_2023_2JVG.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: SBI_STAAM_Tsuboyama_2023_2JVG

dataset:
  answers: proteingym-dms/SBI_STAAM_Tsuboyama_2023_2JVG/prepared/private/answers.csv
  sample_submission: proteingym-dms/SBI_STAAM_Tsuboyama_2023_2JVG/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.SBI_STAAM_Tsuboyama_2023_2JVG.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
