
id: proteingym-dms/ARGR_ECOLI_Tsuboyama_2023_1AOY
name: ARGR_ECOLI_Tsuboyama_2023_1AOY
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/ARGR_ECOLI_Tsuboyama_2023_1AOY/description.md
preparer: biomlbench.tasks.proteingym-dms.ARGR_ECOLI_Tsuboyama_2023_1AOY.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: ARGR_ECOLI_Tsuboyama_2023_1AOY

dataset:
  answers: proteingym-dms/ARGR_ECOLI_Tsuboyama_2023_1AOY/prepared/private/answers.csv
  sample_submission: proteingym-dms/ARGR_ECOLI_Tsuboyama_2023_1AOY/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.ARGR_ECOLI_Tsuboyama_2023_1AOY.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
