
id: proteingym-dms/P53_HUMAN_Giacomelli_2018_Null_Etoposide
name: P53_HUMAN_Giacomelli_2018_Null_Etoposide
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/P53_HUMAN_Giacomelli_2018_Null_Etoposide/description.md
preparer: biomlbench.tasks.proteingym-dms.P53_HUMAN_Giacomelli_2018_Null_Etoposide.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: P53_HUMAN_Giacomelli_2018_Null_Etoposide

dataset:
  answers: proteingym-dms/P53_HUMAN_Giacomelli_2018_Null_Etoposide/prepared/private/answers.csv
  sample_submission: proteingym-dms/P53_HUMAN_Giacomelli_2018_Null_Etoposide/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.P53_HUMAN_Giacomelli_2018_Null_Etoposide.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
