
id: proteingym-dms/CASP3_HUMAN_Roychowdhury_2020
name: CASP3_HUMAN_Roychowdhury_2020
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/CASP3_HUMAN_Roychowdhury_2020/description.md
preparer: biomlbench.tasks.proteingym-dms.CASP3_HUMAN_Roychowdhury_2020.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: CASP3_HUMAN_Roychowdhury_2020

dataset:
  answers: proteingym-dms/CASP3_HUMAN_Roychowdhury_2020/prepared/private/answers.csv
  sample_submission: proteingym-dms/CASP3_HUMAN_Roychowdhury_2020/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.CASP3_HUMAN_Roychowdhury_2020.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
